### ISSUE TITLE
/creative gives error message when used

### ISSUE THREAD

**Issue by Ultimushadow** [ActuallySleeping/Building-Dimension#5]
Hey there, I mentioned a bit ago I was having trouble with the error message and just wanted to get the issue report made out since it's been a bit and I still can't find the culprit

I'm using the latest version, 1.0.7 and _way_ too many mods, you can see the log for the list but I almost don't know that it's going to help very much

The log is quite long so I've isolated exactly when I tried to use the command: [latest.log](https://github.com/ActuallySleeping/Building-Dimension/files/12646038/latest.log)

Here's what the log says when using in the overworld:
[03:44:23] [Server thread/INFO] (building_dimension) Player : UltimuShadow is switching to creative dimension
[03:44:23] [Server thread/INFO] (building_dimension) Saving position for UltimuShadow at (-10.063967538003608, 87.5777683166755, -6.885902726474604)
[03:44:23] [Server thread/INFO] (building_dimension) Saving inventory for UltimuShadow
[03:44:23] [Render thread/INFO] (Minecraft) [CHAT] An unexpected error occurred trying to execute that command
[latest.log](https://github.com/ActuallySleeping/Building-Dimension/files/12646038/latest.log)

And in the building world:
[03:44:56] [Server thread/INFO] (building_dimension) Player : UltimuShadow is switching to survival dimension
[03:44:56] [Server thread/INFO] (building_dimension) Loading game mode for UltimuShadow
[03:44:56] [Server thread/INFO] (building_dimension) Saving inventory for UltimuShadow
[03:44:56] [Render thread/INFO] (Minecraft) [CHAT] An unexpected error occurred trying to execute that command

Are you using a custom command to move the player to the building dimension that could be causing a conflict? Or have any ideas on what kind of mod would interfere with it, so I can isolate it a little easier?

**Comment by leclerc-leo** [comment]
Hello,

It's probably because it cannot find the destination, I'm using a custom function made with the Fabric API which shouldn't require anything except the Fabric API mod which should be included with every modpacks.
Are you planning on getting started very soon (on your server / solo) ? 
I could either release a quick patch that would allows to identify the source and then release a patch once i found the source 
Or you wait for a few hours (maximum tomorrow night) and i release the 2.0.0 version of the mod I'm working on that could fix it and if it doesn't will have way better checks that should allows to find the source of the bug since I'll completely changing how the mods works (and would lose any inventory in the creative dimension)

**Comment by leclerc-leo** [comment]
I am a bit early and 2.0.0 should be out.
The one thing i remove was the achievements that are not saved for now since they are a bit painly to work with but i will work on them very soon.
The new version has a lot more debugging integrated that should allow you to give me where exactly is the error and correct it pretty fast.
Also it has support for the Nether and the end (other customs dimensiosn should work but i haven't tested yet)

**Comment by leclerc-leo** [comment]
Hello, have you tried with the 2.0 version ?

**Comment by Ultimushadow** [comment]
I'm so sorry, I had a bit of burnout and took a break from my projects - the /creative command works just fine now, and the dimensions work great too! I'm not as worried about the advancement stuff but I'll let you know if you would like me to test that out - for now though I'll go ahead and close this out since it looks like you got it all patched up. Thanks a ton for working on it!

**Comment by leclerc-leo** [comment]
Thanks a lot for your reply and the encouragements.

I got them working and tested a bit, the next version should come soonish, I had a lot of work for school.
The next version is probably going to be interesting because it will support Trinkets which if you are planing on using it on a SMP would fix anyone giving themself op shit.

**Comment by Ultimushadow** [comment]
Ah you know what, that's a good point, I have Trinkets installed as well and a shulker box slot on top of that so that's 27 slots to smuggle through at a time, I hadn't tested that before but it definitely warrants interest. I'll check it out when it drops!
